test/cypress/e2e: disable part of the 'validates sixth step (merch)' test
For the Chromium web browser family running only in the headless mode,
beacause it is fails.

```
AssertionError: Timed out retrying after 60000ms: expected '<span>' to be 'visible'

This element `<span>` is not visible because its parent

`<div.q-dialog__inner.flex.no-pointer-events.q-dialog__inner--minimized.q-dialog__inner
--standard.fixed-full.flex-center.q-dialog__inner--square.q-transition--scale-enter-from.q-transition
--scale-enter-active>` has CSS property: `opacity: 0` at Context.eval

(webpack://ride-to-work-by-bike/./test/cypress/e2e/register_challenge.spec.cy.js:881:35)
```