Revert "Update dependency cypress to v15.20.1 (#1578)"
This reverts commit 714ffd7ef9a7be375806c262509063ab568953cc.

Error message:

```
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

ConfigError: Config (unnamed): Unexpected key "default" found.
    at rethrowConfigError (/tmp/del/ride-to-work-by-bike-frontend/node_modules/@eslint/config-array/dist/cjs/index.cjs:343:8)
    at /tmp/del/ride-to-work-by-bike-frontend/node_modules/@eslint/config-array/dist/cjs/index.cjs:1405:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/tmp/del/ride-to-work-by-bike-frontend/node_modules/@eslint/config-array/dist/cjs/index.cjs:1398:43)
    at FlatConfigArray.getConfig (/tmp/del/ride-to-work-by-bike-frontend/node_modules/@eslint/config-array/dist/cjs/index.cjs:1427:15)
    at entryFilter (/tmp/del/ride-to-work-by-bike-frontend/node_modules/eslint/lib/eslint/eslint-helpers.js:323:27)
    at async NodeHfs.<anonymous> (file:///tmp/del/ride-to-work-by-bike-frontend/node_modules/@humanfs/core/src/hfs.js:574:24)
    at async NodeHfs.walk (file:///tmp/del/ride-to-work-by-bike-frontend/node_modules/@humanfs/core/src/hfs.js:614:3)
    at async globSearch (/tmp/del/ride-to-work-by-bike-frontend/node_modules/eslint/lib/eslint/eslint-helpers.js:364:20)
    at async Promise.allSettled (index 0)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```